// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows; // Support Linux via config Windows/Web
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5_1Echt5EoNg5alEzDBbZMtgwLvqBoo',
    appId: '1:691920847491:web:f20d351e7f9ede5767d1b6',
    messagingSenderId: '691920847491',
    projectId: 'arkchantier',
    authDomain: 'arkchantier.firebaseapp.com',
    storageBucket: 'arkchantier.firebasestorage.app',
    measurementId: 'G-E04C83T86Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFC1y5nzyoi-1wZXUZv64o6Ar07Sybv40',
    appId: '1:691920847491:android:c3ae4a9fdb23e59867d1b6',
    messagingSenderId: '691920847491',
    projectId: 'arkchantier',
    storageBucket: 'arkchantier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsP74mki7j03iePx-kO-ECY8TA-q8r5hM',
    appId: '1:691920847491:ios:ad07bacab7ed08a567d1b6',
    messagingSenderId: '691920847491',
    projectId: 'arkchantier',
    storageBucket: 'arkchantier.firebasestorage.app',
    iosBundleId: 'com.example.monChantierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsP74mki7j03iePx-kO-ECY8TA-q8r5hM',
    appId: '1:691920847491:ios:ad07bacab7ed08a567d1b6',
    messagingSenderId: '691920847491',
    projectId: 'arkchantier',
    storageBucket: 'arkchantier.firebasestorage.app',
    iosBundleId: 'com.example.monChantierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ5_1Echt5EoNg5alEzDBbZMtgwLvqBoo',
    appId: '1:691920847491:web:97537d3aba4a880a67d1b6',
    messagingSenderId: '691920847491',
    projectId: 'arkchantier',
    authDomain: 'arkchantier.firebaseapp.com',
    storageBucket: 'arkchantier.firebasestorage.app',
    measurementId: 'G-DWWLK0G7ZW',
  );
}
